language: none # Ada

integrations:                               
    notifications:
        - integrationName: email
          type: email
          on_success: change
          on_failure: change
          on_cancel: never

branches:
    only:
        - master
        - stable
        - testing

env:
    global:
        - IMAGE_NAME="alire/gnat"
    matrix:
        - IMAGE_TAG="community-2018"
        - IMAGE_TAG="debian-testing"
        - IMAGE_TAG="ubuntu-lts"

build:
    pre_ci_boot:
        image_name: $IMAGE_NAME
        image_tag: $IMAGE_TAG
        pull: true
    ci:
        - scripts/shiptest.sh

### JOBS ###
# This should trigger a CI job in alire-crates-ci

jobs:
  - name: alire_runCI
    type: runCI
    steps:
      - IN: alire_ciRepo

  - name: crates-ci
    type: runSh
    dependencyMode: strict
    steps:
      - IN: alire_runCI
      - TASK:
        - script: 
          - echo "triggering crate CI now"
