language: none # Ada

integrations:                               
    notifications:
        - integrationName: email
          type: email
          on_success: change
          on_failure: change
          on_cancel: never

branches:
    only:
        - master
        - stable
        - testing

env:
    global:
        - IMAGE_NAME="alire/gnat"
    matrix:
        - IMAGE_TAG="community-current"
        - IMAGE_TAG="debian-stable"
        - IMAGE_TAG="ubuntu-lts"

build:
    pre_ci_boot:
        image_name: $IMAGE_NAME
        image_tag: $IMAGE_TAG
        pull: true
    ci:
        - pip install git+https://github.com/AdaCore/e3-testsuite.git@1c751b82
        - scripts/shiptest.sh
    on_success:
        - shipctl put_resource_state branchInfo branch "none"
        - if [ "$IS_PULL_REQUEST" == false ]; then shipctl put_resource_state branchInfo BRANCH $BRANCH; fi

resources:
  - name: branchInfo
    type: params
    versionTemplate:
      params:
        BRANCH: "none" 
  
jobs:
  - name: alire_runCI
    type: runCI
    steps:
      - OUT: branchInfo
