
--  Generated by awsres from /support/embedder/embedder.sh

pragma Style_Checks (Off);

with Ada.Streams;

package r.crate_lib_src_name_ads is

   use Ada.Streams;

   Content : aliased constant Stream_Element_Array :=
       (112,  97,  99, 107,  97, 103, 101,  32,  64,  95,  67,  65,  80,  73,
         84,  65,  76,  73,  90,  69,  58,  78,  65,  77,  69,  95,  64,  32,
        105, 115,  10,  10, 101, 110, 100,  32,  64,  95,  67,  65,  80,  73,
         84,  65,  76,  73,  90,  69,  58,  78,  65,  77,  69,  95,  64,  59,
         10);

end r.crate_lib_src_name_ads;
