pragma Warnings (Off);

--  Generated by awsres from /support/embedder/embedder.sh

pragma Style_Checks (Off);

with r.crate_bin_alire_toml;
with r.crate_bin_name_gpr;
with r.crate_bin_src_name_adb;
with r.crate_common_gitignore_hidden;
with r.crate_lib_alire_toml;
with r.crate_lib_name_gpr;
with r.crate_lib_src_name_ads;
with r.crate_test_tests_alire_toml;
with r.crate_test_tests_common_name_tests_ads;
with r.crate_test_tests_crate_test_tests_gpr;
with r.crate_test_tests_src_name_testsxassertions_enabled_adb;
with r.github_readme_md;
with r.github_publish_yml;
with r.github_selftest_yml;

with Alire.Templates;
with GNAT.Calendar;

package body r is

   Initialized : Boolean := False;

   procedure Init is
      use Alire.Templates;
   begin
      if not Initialized then
         Initialized := True;
         Register
            ("crate_bin/alire.toml",
             r.crate_bin_alire_toml.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_bin/name.gpr",
             r.crate_bin_name_gpr.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_bin/src/name.adb",
             r.crate_bin_src_name_adb.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_common/gitignore.hidden",
             r.crate_common_gitignore_hidden.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_lib/alire.toml",
             r.crate_lib_alire_toml.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_lib/name.gpr",
             r.crate_lib_name_gpr.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_lib/src/name.ads",
             r.crate_lib_src_name_ads.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_test/tests/alire.toml",
             r.crate_test_tests_alire_toml.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_test/tests/common/name_tests.ads",
             r.crate_test_tests_common_name_tests_ads.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_test/tests/crate_test_tests.gpr",
             r.crate_test_tests_crate_test_tests_gpr.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("crate_test/tests/src/name_tests-assertions_enabled."
             & "adb",
             r.crate_test_tests_src_name_testsxassertions_enabled_adb.Content'Access,
             GNAT.Calendar.Time_Of (2025, 04, 29, 05, 06, 37, 0.0));
         Register
            ("github/README.md",
             r.github_readme_md.Content'Access,
             GNAT.Calendar.Time_Of (2025, 07, 10, 12, 00, 08, 0.0));
         Register
            ("github/publish.yml",
             r.github_publish_yml.Content'Access,
             GNAT.Calendar.Time_Of (2025, 07, 10, 12, 00, 27, 0.0));
         Register
            ("github/selftest.yml",
             r.github_selftest_yml.Content'Access,
             GNAT.Calendar.Time_Of (2025, 07, 10, 12, 06, 00, 0.0));
      end if;
   end Init;

begin
   Init;
end r;
