with Alire.Properties;
with Alire.Solver;

package Alire.Lockfiles is

   type Validities is (Missing, Invalid, Valid);

   --  A crate lockfile stores the dependency solution in use. This permanent
   --  storage, in <alire>/crate_name.lock, is the basis for orderly uploads
   --  and pinning. This file is autogenerated and manipulated via alr
   --  commands; the user should not modify it.

   function File_Name (Name     : Crate_Name;
                       Root_Dir : Any_Path) return Any_Path;
   --  Return the location /path/to/crate/dir/alire/crate.lock, filename
   --  included, given the root directory where the crate is deployed.

   function Read (Filename : Any_Path) return Solver.Solution;
   --  Read a solution from the given lockfile

   function Validity (File : Any_Path) return Validities;
   --  Check if given file is a valid lockfile

   procedure Write (Solution    : Solver.Solution;
                    Filename    : Any_Path);
   --  Write a solution to a file

end Alire.Lockfiles;
