# This workflow verifies that all pinned dependencies match the submodule
# versions.

name: Integrity Checks
on:
  pull_request:

jobs:
  verify-pins:
    name: Pins & Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify pinned dependencies
        run: scripts/verify-pins.sh

  templates:
    name: Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify templates are up to date
        run: |
          ( support/embedder/embedder.sh | \
            grep "No changes in templates, skipping generation" ) || \
          ( echo "Templates are not up to date, please run 'support/embedder/embedder.sh' to update them."
            echo "Commit and push the changes to generated files and their hash before opening a PR."
            exit 1 )
