name: spellcheck

on:
  pull_request:
    paths:
      - '**.md'
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run misspell
      uses: reviewdog/action-misspell@v1
      with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-annotations
          locale: "US"
          pattern: '*.md'
          fail_level: warning
